### PR TITLE
And.apply

### PR DESCRIPTION
**Pull request by daejunpark**
Do not merge. Just for a question.

@cos  It seems that this change makes no difference. Could you tell me why you split the terms into sub and terms?

### CODE REVIEW

**Comment by cos** [comment]
The split into `sub` and `terms` is irrelevant -- the code was written before we had `asSet` for `And`.

Still, the way you wrote it is not correct as, for `_1 = (a AND b) ` and `_2 = c`, it will give you `Set(a AND b), c)` instead of `Set(a, b, c)`. 

`And.asSet(_1) | And(_2).asSet` should do it.

**Comment by daejunpark** [comment]
@cos Thanks. Then we can remove the part that splits into sub and terms, right? I'll do that.

Also, my version is still correct. The asSet of And will be applied through cartezianProduct followed by applyOnNonOrs.

**Comment by daejunpark** [comment]
@cos I updated this PR. Please merge if you are happy with that. Or, you can directly fix and merge it.

**Comment by cos** [comment]
I see, you're using the `apply(Iterable)` implementation. I'm not 100% sure it has the same performance, but it should be fine.

**Comment by cos** [comment]
Do the tests pass?

**Comment by daejunpark** [comment]
Sure, all tests are passed except the ignored ones.

**Pull request merged**
